# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 0.1
    
# e.g. "anas_krystallinus"    
species.name <- anja_collazinos
    
# e.g. "red"    
color <- c("#E1253")
    
# tip: pick a color using rstudio colour picker. 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
